#
# Module manifest for module 'signal'
#
# Generated by: PSeudoScripter
#
# Generated on: 26.09.2025
#

@{

	# Script module or binary module file associated with this manifest.
	RootModule = 'signal.psm1'

	# Version number of this module.
	ModuleVersion = '1.0.0.2'

	# Supported PSEditions
	# CompatiblePSEditions = @()

	# ID used to uniquely identify this module
	GUID = '53b68b57-1a28-47cd-885e-68008d4c0c44'

	# Author of this module
	Author = 'PSeudoScripter'

	# Company or vendor of this module
	CompanyName = 'PSeudoScripter'

	# Copyright statement for this module
	Copyright = 'GNU General Public License v3.0'

	# Description of the functionality provided by this module
	Description = 'Signal module to interact with the Signal Messenger API (bbernhard/signal-cli-rest-api).'

	# Minimum version of the PowerShell engine required by this module
	PowerShellVersion = '5.1'

	# Name of the PowerShell host required by this module
	# PowerShellHostName = ''

	# Minimum version of the PowerShell host required by this module
	# PowerShellHostVersion = ''

	# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
	DotNetFrameworkVersion = '4.5.2'

	# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
	# ClrVersion = ''

	# Processor architecture (None, X86, Amd64) required by this module
	ProcessorArchitecture = 'None'

	# Modules that must be imported into the global environment prior to importing this module
	RequiredModules = @()

	# Assemblies that must be loaded prior to importing this module
	RequiredAssemblies = @()

	# Script files (.ps1) that are run in the caller's environment prior to importing this module.
	ScriptsToProcess = @()

	# Type files (.ps1xml) to be loaded when importing this module
	TypesToProcess = @()

	# Format files (.ps1xml) to be loaded when importing this module
	FormatsToProcess = @()

	# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
	NestedModules = @()

	# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
	FunctionsToExport = @(
        'Add-SignaMemberToGroup',
        'Connect-SignalDevice',
        'Get-SignalAbout',
        'Get-SignalAccount',
        'Get-SignalConfiguration',
        'Get-SignalDevices',
        'Get-SignalGroup',
        'Get-SignalLocalConfiguration',
        'Join-SignalGroup',
        'New-SignalConfiguration',
        'New-SignalGroup',
        'Receive-SignalMessage',
        'Register-SignalDevice',
        'Remove-SignalDevice',
        'Remove-SignalGroups',
        'Remove-SignaMemberFromGroup',
        'Send-SignalMessage',
        'Set-SignalConfiguration',
        'Set-SignalGroup',
        'Unregister-SignalDevice'
    )

	# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
	CmdletsToExport = @() 

	# Variables to export from this module
	VariablesToExport = @()

	# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
	AliasesToExport = @()

	# DSC resources to export from this module
	# DscResourcesToExport = @()

	# List of all modules packaged with this module
	ModuleList = @()

	# List of all files packaged with this module
	FileList = @()

	# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
	PrivateData = @{

	    PSData = @{

	        # Tags applied to this module. These help with module discovery in online galleries.
	        Tags = @('Signal', 'Messaging','bbernhard', 'REST', 'API')

	        # A URL to the license for this module.
	        LicenseUri = 'https://github.com/PSeudoScripter/signal/blob/main/LICENSE'

	        # A URL to the main website for this project.
	        ProjectUri = 'https://github.com/PSeudoScripter/signal'

	        # A URL to an icon representing this module.
	        # IconUri = ''

	        # ReleaseNotes of this module
	        ReleaseNotes = 'Parameter force added to new-signalconfiguration'

	        # Prerelease string of this module
	        # Prerelease = ''

	        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
	        RequireLicenseAcceptance = $false

	        # External dependent modules of this module
	        # ExternalModuleDependencies = @()

	    }

	}
	# HelpInfo URI of this module
	HelpInfoURI = 'https://github.com/PSeudoScripter/signal'
}


